---
# tasks file for ad_auth
- name: install packages
  package:
    name: "{{ ad_auth_packages }}"
    state: present
  register: ad_auth_install_packges
  until: ad_auth_install_packges is succeeded
  retries: 3

- name: copy authconfig files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ ad_auth_files }}"
  loop_control:
    label: "{{ item.src }}"

- name: template authconfig files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ ad_auth_templates }}"
  loop_control:
    label: "{{ item.src }}"

- name: configure samba
  ini_file:
    path: /etc/samba/smb.conf
    section: global
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop: "{{ ad_auth_smb_options }}"
  loop_control:
    label: "{{ item.option }}"

- name: join domain
  command: "{{ ad_auth_join_command }}"
  changed_when: no
