---
# tasks file for ad_auth
- name: install packages
  package:
    name: "{{ ad_auth_packages }}"
    state: present
  register: ad_auth_install_packges
  until: ad_auth_install_packges is succeeded
  retries: 3
  notify:
    - restart realmd

- name: install pip packages
  pip:
    name: "{{ ad_auth_pip_packages }}"
    state: present
  register: ad_auth_install_pip_packges
  until: ad_auth_install_pip_packges is succeeded
  retries: 3

- name: configure nsswitch to use sss
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: "^{{ item }}:"
    line: "{{ item }}:\tfiles sss"
  loop: "{{ ad_auth_nsswich_maps }}"

- name: configure sssd to work with nss
  ini_file:
    path: /etc/sssd/sssd.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop: "{{ ad_auth_sssd_configuration }}"
  loop_control:
    label: "{{ item.option }}"
  notify:
    - restart sssd

- name: configure pam to use sssd
  pamd:
    name: "{{ item }}"
    type: auth
    new_type: auth
    control: required
    new_control: sufficient
    module_path: pam_deny.so
    new_module_path: pam_sss.so
    module_arguments: use_first_pass
    state: before
  loop: "{{ ad_auth_pam_files }}"

- name: start services
  service:
    name: "{{ item }}"
    state: started
  loop: "{{ ad_auth_services }}"
  when:
    - ad_auth_join | bool

- name: join domain
  expect:
    command: "{{ ad_auth_join_command }}"
    responses:
      Password for *: "{{ ad_auth_registration_password }}"
  when:
    - ad_auth_join | bool
