---
# tasks file for ad_auth
- name: install packages
  package:
    name: "{{ ad_auth_packages }}"
    state: present
  register: ad_auth_install_packges
  until: ad_auth_install_packges is succeeded
  retries: 3

- name: Configure smb.conf
  ini_file:
    path: /etc/samba/smb.conf
    section: global
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop: "{{ ad_auth_smb_options }}"
