---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-ad_auth
      ad_auth_workgroup: MY_GROUP
      ad_auth_realm: MY_REALM
      ad_auth_registration_hash: a1b2c3
      ad_auth_registration_user: my_user
      ad_auth_ou: ou=Nerds,ou=Staff
      ad_auth_server: my_server.example.com
