---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: check adcli
      command: /usr/sbin/adcli --help
    - name: check authconfig
      command: /usr/sbin/authconfig --help
    - name: check realmd
      command: /usr/sbin/realm list
    - name: check samba common tools
      command: /usr/bin/net --version
